import Head from "next/head";
{
  /*
import Image from "next/image";
*/
}
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>なりなり</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>鈴木捺梨沙</h1>

        {/*
        <Image
          className="sampleImage"
          src="/image-sample.JPG"
          alt="image-sample"
          width={1000}
          height={300}
        ></Image>
        */}

        <div className={styles.grid}>
          <a
            href="https://www.facebook.com/profile.php?id=100006778170775"
            className={styles.card}
          >
            <h2>Facebook</h2>
          </a>

          <a
            href="https://www.instagram.com/narisa9696/?hl=en"
            className={styles.card}
          >
            <h2>Instagram</h2>
          </a>

          <a href="https://twitter.com/oonekonarisa" className={styles.card}>
            <h2>Twitter</h2>
          </a>

          <a href="https://oonekonarisa.medy.jp/" className={styles.card}>
            <h2>Blog</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Wriiten by Narisa Suzuki
        </a>
      </footer>
    </div>
  );
}
