import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>なりなり</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Image
            className="topImage"
            src="/top.jpg"
            alt="top-img"
            width={750}
            height={500}
          ></Image>
          <section className={styles.menu}>
            <div className="btn1Container">
              <Link href="https://oonekonarisa.medy.jp/" passHref>
                <Image
                  src="/1.png"
                  alt="tegaki1"
                  width={210}
                  height={70}
                  objectFit="contain"
                ></Image>
              </Link>
            </div>

            <div className="btn2Container">
              <Link href="" passHref>
                <Image
                  src="/2.png"
                  alt="tegaki2"
                  width={210}
                  height={70}
                ></Image>
              </Link>
            </div>

            <div className="btn3Container">
              <Link
                href="https://www.instagram.com/kissa_ooneko/?hl=en"
                passHref
              >
                <Image
                  src="/3.png"
                  alt="tegaki3"
                  width={210}
                  height={70}
                ></Image>
              </Link>
            </div>
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        ></a>
      </footer>
    </div>
  );
}
